// Auto-generated by scripts/generate-build-info.sh
// DO NOT EDIT MANUALLY - changes will be overwritten

window.BUILD_INFO = {
    version: '0.1.0',
    tree: '28654441d73cd5589fb26ddee6a2a9701c440fa7',
    date: '2026-01-08'
};
