// Auto-generated by scripts/generate-build-info.sh
// DO NOT EDIT MANUALLY - changes will be overwritten

window.BUILD_INFO = {
    version: '0.1.0',
    contentId: 'ad0a458b3a160086e63d30a599db825fbfa110e9',
    date: '2026-01-08'
};
