#!/bin/bash
SHA=$(git rev-parse HEAD)
mkdir -p js
echo "// Auto-generated by scripts/generate-build-info.sh" > js/build-info.js
echo "var BUILD_INFO = {" >> js/build-info.js
echo "  commit: '$SHA'" >> js/build-info.js
echo "};" >> js/build-info.js
