#!/bin/bash
TREE_HASH=$(git write-tree)
DATE=$(date -u +%Y-%m-%d)
VERSION="0.1.0" # Placeholder version

mkdir -p js
cat > js/build-info.js <<EOL
// Auto-generated by scripts/generate-build-info.sh
// DO NOT EDIT MANUALLY - changes will be overwritten

window.BUILD_INFO = {
    version: '$VERSION',
    tree: '$TREE_HASH',
    date: '$DATE'
};
EOL
